### PR TITLE
Fix Kovan and xDai Hardhat forking

### LINKED ISSUE #1008: forking xDAI to hardhat network doesn't work
```❯ npx hardhat node --fork https://rpc.xdaichain.com```
```
Error HH604: Error running JSON-RPC server: Chain with ID 100 not supported
```

### LINKED ISSUE #1038: Forking doesn't work on Kovan or other networks
I just ran into the following issue while trying to fork Kovan using an Alchemy API

```
  Error: Invalid RpcBlockWithTransactions or null
      at codec.decode.fold (/Users/dmihal/keystone/defi-777/contracts/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/types.ts:8:11)
      at Left.fold (/Users/dmihal/keystone/defi-777/contracts/node_modules/io-ts/node_modules/fp-ts/lib/Either.js:113:16)
      at Object.decode (/Users/dmihal/keystone/defi-777/contracts/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/types.ts:6:30)
      at JsonRpcClient._perform (/Users/dmihal/keystone/defi-777/contracts/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/client.ts:230:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

The issue is also reported by @PatrickAlphaC here:
https://ethereum.stackexchange.com/questions/89951/hardhat-deploy-script-works-on-testnet-but-not-on-forked-hardhat-network

### LINKED ISSUE #1177: Unable to fork "xdai"
Started a fork with:
```bash
$ npx hardhat node  --version
2.0.6
$ npx hardhat node  --fork https://dai.poa.network
Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/

...
```

Now tried to use it (from truffle console), but I immediately get:

```
eth_blockNumber
  Error: Invalid RpcBlockWithTransactions or null
      at /Users/dror/Downloads/thh/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/types.ts:8:11
      at Left.fold (/Users/dror/Downloads/thh/node_modules/io-ts/node_modules/fp-ts/lib/Either.js:113:16)
      at Object.decode (/Users/dror/Downloads/thh/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/types.ts:6:30)
      at JsonRpcClient._perform (/Users/dror/Downloads/thh/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/client.ts:230:27)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at ForkBlockchain._getBlockByNumber (/Users/dror/Downloads/thh/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:215:22)
      at ForkBlockchain.getLatestBlock (/Users/dror/Downloads/thh/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:40:19)
      at HardhatNode.getLatestBlockNumber (/Users/dror/Downloads/thh/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:460:20)
      at EthModule._blockNumberAction (/Users/dror/Downloads/thh/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:295:25)
      at HardhatNetworkProvider._sendWithLogging (/Users/dror/Downloads/thh/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:122:22)

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/reportbug
```

### PR DESCRIPTION
**Pull request by scnale**
This pull request relaxes type checks for the blocks so that Aura consensus seals are not rejected as invalid.

One caveat with this fix is that we aren't actually implementing the Aura consensus block seal, so the block hashes will differ, even if the blocks themselves look otherwise identical.

This essentially fixes Kovan and xDai forking for most purposes.

See [xDai consensus docs](https://www.xdaichain.com/for-validators/consensus/aura-consensus).

Fixes #1177, fixes #1038, fixes #1008.

### CODE REVIEW

**Comment by fvictorio** [comment]
There seems to be a failing test that doesn't look like a false negative.

File: packages/hardhat-core/test/internal/hardhat-network/provider/node.ts [hunk 1]
```diff
@@ -30,7 +30,10 @@ describe("HardhatNode", function () {
   };
   const kovanForkPoint: ForkPoint = {
     networkName: "kovan",
-    url: ALCHEMY_KOVAN_URL,
+    url: (ALCHEMY_URL !== undefined ? ALCHEMY_URL : "").replace(
```
Comment (fvictorio) [inline packages/hardhat-core/test/internal/hardhat-network/provider/node.ts:33]:
```suggestion
    url: (ALCHEMY_URL ?? "").replace(
```

**Review by fvictorio — APPROVED** [review]

**Comment by scnale** [comment]
This branch should be rebased on master once #1224 is merged before running the CI. It depends on a fix for the `ethereumjs-vm`  where the root of the receipts trie wasn't being updated.

**Review by alcuadrado — APPROVED** [review]
